<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
	</array>
	<key>name</key>
	<string>ClassesAndTests</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>\b(Axel Ancona Esselmann)\b</string>
			<key>name</key>
			<string>credits</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?&lt;=Executing\s)[\s\w\,\d\.\:]+(?=[AP]M\:)[AP]M:</string>
			<key>name</key>
			<string>date</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(Result:|Executing)\b</string>
			<key>name</key>
			<string>actions</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\d+(?=\s\/)|(?&lt;=\/\s)\d+</string>
			<key>name</key>
			<string>numbers_tests_run</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?&lt;=\()\s+\d+%(?=\))</string>
			<key>name</key>
			<string>percentages</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?&lt;=\w:)\d+(?=\s)</string>
			<key>name</key>
			<string>line_numbers</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?&lt;=,\sline\s)\d+(?=,\s)</string>
			<key>name</key>
			<string>line_numbers</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?&lt;!\$)/[/\w\s]+/(?=\w+\.\w+)</string>
			<key>name</key>
			<string>folder</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?&lt;=File\s")/[/\w\s]+/(?=\w+\.\w+)</string>
			<key>name</key>
			<string>folder</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?&lt;=\/)\w+\.\w+</string>
			<key>name</key>
			<string>file</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?&lt;=Failed\sasserting\sthat\s).+(?=\smatches\sexpected\s)</string>
			<key>name</key>
			<string>wrong_value</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?&lt;=\s!\=\s).+</string>
			<key>name</key>
			<string>wrong_value</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?&lt;=\smatches\sexpected\s).+(?=\.\s)</string>
			<key>name</key>
			<string>expected_value</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?&lt;=AssertionError:\s)["'\w\d\s]+(?=!\=\s)</string>
			<key>name</key>
			<string>expected_value</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^Time:\s\d+\s\w+,\sMemory:\s\d+\.\d+\w+</string>
			<key>name</key>
			<string>statistics</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^FAILURES\!\s</string>
			<key>name</key>
			<string>failure_statement</string>
		</dict>
		<dict>
			<key>match</key>
			<string>FAILED\s\([\w]+=\d+\)\s</string>
			<key>name</key>
			<string>failure_statement</string>
		</dict>
		<dict>
			<key>match</key>
			<string>PHPUnit\s\d+\.\d+\.\d+\sby\sSebastian\sBergmann.</string>
			<key>name</key>
			<string>php_unit</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^ClassesAndTests\s\d+\.\d+\.\d+</string>
			<key>name</key>
			<string>classes_and_tests</string>
		</dict>
		<dict>
			<key>match</key>
			<string>FAIL:(?=\s[\w]+\s\()</string>
			<key>name</key>
			<string>failed</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\={70}</string>
			<key>name</key>
			<string>double_line</string>
		</dict>
		<dict>
			<key>match</key>
			<string>-{70}</string>
			<key>name</key>
			<string>single_line</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^\d+\)</string>
			<key>name</key>
			<string>numbers</string>
		</dict>
		<dict>
			<key>match</key>
			<string>[\w\\]+(?=\\\w+::)</string>
			<key>name</key>
			<string>namespace</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\w+(?=::)</string>
			<key>name</key>
			<string>class_name</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?&lt;=::)\w+(?=\s)</string>
			<key>name</key>
			<string>function_name</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?&lt;=FAIL:\s)[\w]+(?=\s\()</string>
			<key>name</key>
			<string>function_name</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^OK[\s\(\d\w\,\)]+</string>
			<key>name</key>
			<string>passed</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\.+(?=F)|^\.+(?=\s\d+\s\/\s\d+\s\(\s\d+%\))|^\.+(?=\s)|(?&lt;=[F])\.+(?=\s)</string>
			<key>name</key>
			<string>green</string>
		</dict>
		<dict>
			<key>match</key>
			<string>F+(?=\.)|\s\sF+\s\s|(?&lt;=\.)F+(?!\w)</string>
			<key>name</key>
			<string>failed</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(Failures[a-z,: 0-9]*)</string>
			<key>name</key>
			<string>failed</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b::\b</string>
			<key>name</key>
			<string>resolution_operator</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^\$[\s\/\w\"]+(?=\w")\w"</string>
			<key>name</key>
			<string>command</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.cat</string>
	<key>uuid</key>
	<string>47fc9162-d2d9-427a-b400-f2714eec92c1</string>
</dict>
</plist>
